
services:

  frontend:
    build:
      context: .
      dockerfile: services/Dockerfile.frontend
    ports:
      - "80:80"
    depends_on:
      - backend
    networks:
      - medinsight-net

  backend:
    build:
      context: .
      dockerfile: services/Dockerfile.backend
    env_file:
      - .env
    ports:
      - "8000:8000"

    environment:
      FRONTEND_URL: http://localhost:80
      REDIS_URL: redis://cache:6379/0

    volumes:
      - ./data:/app/data

    depends_on:
      - cache

    networks:
      - medinsight-net

  cache:
    image: redis:7-alpine
    command: redis-server --appendonly yes --maxmemory 512mb --maxmemory-policy allkeys-lru
    volumes:
      - redis-data:/data
    networks:
      - medinsight-net

volumes:
  redis-data:

networks:
  medinsight-net:
    driver: bridge
